### ISSUE TITLE
Bug: Timing Issues in TIM

### ISSUE THREAD

**Issue by omerday** [omerday/Neuroscience-of-Anxiety-Lab#108]
### Contact Details

Shir

### What happened?

According to Shir and Rany:

- [ ] Time between fixation and first square is 7s (needs to be 4-6)
- [ ] Time between heat and rating is around 20s
- [ ] Heat Pain event should be right when the heat arrives, and not 10s prior
- [ ] Full square should end right when the heat ends
- [ ] 5s between square and VAS
- [ ] One of the sides in the yellow square is missing??

### task

TIM

### Consistency

Consistent
