### ISSUE TITLE
Feature: button to arrange the order of the movies (NPU)

### ISSUE THREAD

**Issue by ShellyCohen9** [omerday/Neuroscience-of-Anxiety-Lab#109]
### Contact Details

Shelly Cohen

### What do you want?

בהמשך לשיחתנו, הוספת כפתור במסך ההתחלה בNPU שבו ניתן יהיה לשלוט בסדר הופעת הסרטים - האם יופיעו לפני או אחרי מטלת הNPU. בנוסף, שינוי השם של הכפתור **הקיים**. שינוי השם למשהו ברור יותר שידגיש שאם לא לוחצים אז לא מופיעים סרטים. 

### task

NPU

### Approval

- [X] Rany approved the above feature request

**Comment by omerday** [comment]
After discussion with Shelly, I think I'll do the following:

- [ ] Change the dialog box to select whether we want the videos before/after the task or not at all
- [ ] Create a side executable for the videos only
